### ISSUE TITLE
swift support

### ISSUE THREAD

**Issue by specialfish9** [lucat1/visimp#32]

**Comment by lucat1** [comment]
Unfortunately no `nvim-treesitter` grammar is available and the language server is not among `nvim-lspinstaller` supported ones. Separate issues should be tackled in the appropriate repositories of those packages.

**Comment by lucat1** [comment]
There now is a treesitter grammar available but the LSP is not planned to be included as it's part of the XCode toolchain (and it's hard to install as standalone I guess). I'll add the language without a default LSP because of this. This means that the LSP will not be installed automatically and will error if enabled while the [sourcekit lsp](https://github.com/apple/sourcekit-lsp) is not yet installed.
